- hosts: all
  become: true
  tasks: 
     - name: delete old deployment
       command: kubectl delete -f /home/ubuntu/Deployment.yml
       ignore_errors: yes  # <--- Add this (Prevents crash if deployment doesn't exist)

     - name: delete old service
       command: kubectl delete -f /home/ubuntu/Service.yml
       ignore_errors: yes  # <--- Add this

     - name: create new deployment
       command: kubectl apply -f /home/ubuntu/Deployment.yml

     - name: create new service
       command: kubectl apply -f /home/ubuntu/Service.yml