FROM centos:7
MAINTAINER sanadshamoon92@gmail.com

# --- 1. Fix Repo URL ---
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

# --- 2. Install Packages ---
RUN yum install -y httpd zip unzip

# --- 3. COPY the file from the server (instead of downloading) ---
WORKDIR /var/www/html/
COPY photogenic.zip .

# --- 4. Unzip and Configure ---
RUN unzip photogenic.zip
RUN cp -rvf photogenic/* .
RUN rm -rf photogenic photogenic.zip

CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]
EXPOSE 80 22
