apiVersion: v1
kind: Service
metadata:
  name: mysql-service    # <--- Your PHP code will use this name!
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7      # Using 5.7 for best compatibility
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"  # <--- Remember this password
        - name: MYSQL_DATABASE
          value: "website"       # <--- Creates an empty DB named 'website'
        ports:
        - containerPort: 3306
          name: mysql